CREATE TABLE [prodcopy].[Contact]
(
[Id] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[IsDeleted] [bit] NULL,
[MasterRecordId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastName] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FirstName] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Salutation] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Name] [nvarchar] (121) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherStreet] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherCity] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherState] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherPostalCode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherCountry] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherLatitude] [float] NULL,
[OtherLongitude] [float] NULL,
[OtherGeocodeAccuracy] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherAddress] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailingStreet] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailingCity] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailingState] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailingPostalCode] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailingCountry] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailingLatitude] [float] NULL,
[MailingLongitude] [float] NULL,
[MailingGeocodeAccuracy] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MailingAddress] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Phone] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MobilePhone] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HomePhone] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherPhone] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssistantPhone] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportsToId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Title] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Department] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AssistantName] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LeadSource] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthdate] [date] NULL,
[Description] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OwnerId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedDate] [datetime] NULL,
[CreatedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LastModifiedDate] [datetime] NULL,
[LastModifiedById] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SystemModstamp] [datetime] NULL,
[LastActivityDate] [date] NULL,
[LastCURequestDate] [datetime] NULL,
[LastCUUpdateDate] [datetime] NULL,
[LastViewedDate] [datetime] NULL,
[LastReferencedDate] [datetime] NULL,
[EmailBouncedReason] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EmailBouncedDate] [datetime] NULL,
[IsEmailBounced] [bit] NULL,
[PhotoUrl] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Jigsaw] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JigsawContactId] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RecordTypeId] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__AlternateEmail__c] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Citizenship__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Country_of_Origin__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Current_Address__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Deceased__c] [bit] NULL,
[hed__Do_Not_Contact__c] [bit] NULL,
[hed__Ethnicity__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Exclude_from_Household_Formal_Greeting__c] [bit] NULL,
[hed__Exclude_from_Household_Informal_Greeting__c] [bit] NULL,
[hed__Exclude_from_Household_Name__c] [bit] NULL,
[hed__FERPA__c] [bit] NULL,
[hed__Financial_Aid_Applicant__c] [bit] NULL,
[hed__Gender__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__HIPAA_Detail__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__HIPAA__c] [bit] NULL,
[hed__Military_Background__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Military_Service__c] [bit] NULL,
[hed__Naming_Exclusions__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__PreferredPhone__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Preferred_Email__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Primary_Address_Type__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Primary_Household__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Primary_Organization__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Religion__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Secondary_Address_Type__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Social_Security_Number__c] [nvarchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__UniversityEmail__c] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__WorkEmail__c] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__WorkPhone__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Work_Address__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__is_Address_Override__c] [bit] NULL,
[Primary_Student_Organization__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPLID__c] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASURITE_ID__c] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[edX_Username__c] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[edX_ID__c] [nvarchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Starbucks_ID__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[edX_Date_Joined__c] [datetime] NULL,
[edX_Last_Login__c] [datetime] NULL,
[MC4SF__MC_Subscriber__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SFDC_Enterprise_Contact_Id__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Preferred_name__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Type__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MiddleName] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Suffix] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Inquiry_Date_Time__c] [datetime] NULL,
[Number_of_Inquiries__c] [float] NULL,
[EA_Lead_Source__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HasOptedOutOfEmail] [bit] NULL,
[HasOptedOutOfFax] [bit] NULL,
[DoNotCall] [bit] NULL,
[Primary_Academic_Program__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary_Department__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary_Educational_Institution__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Primary_Sports_Organization__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Dual_Citizenship__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[hed__Race__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContactRecordTypeId__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Contact_Key__c] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Employee_Number__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EventType__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GAClientId__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pilot__c] [bit] NULL,
[Token_Code__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[edX_Email__c] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[uuid__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Military_Branch__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Military_Status__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Permission_to_Text__c] [bit] NULL,
[SSB_CRMSYSTEM_Contact_ID__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_ACCT_ID__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_SSID_Winner__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_SSID_Winner_SourceSystem__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MDM_Primary_Phone__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MDM_Cell_Phone__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MDM_Home_Phone__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MDM_Other_Phone__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MDM_Business_Phone__c] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Corporate_Partner_Name__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mdm_emailprimary__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mdm_emailone__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[mdm_emailtwo__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Corporate_Employee_ID__c] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASUO_Country_of_Citizenship__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASUO_Country_of_Origin__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASUO_Gender__c] [nvarchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASUO_Hispanic__c] [bit] NULL,
[ASUO_Military_Benefits__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASUO_Previous_ASU_Affiliation__c] [bit] NULL,
[ASUO_QTR_Employer__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASUO_QTR_Program__c] [bit] NULL,
[ASUO_Race_American_Indian__c] [bit] NULL,
[ASUO_Race_Asian__c] [bit] NULL,
[ASUO_Race_Black__c] [bit] NULL,
[ASUO_Race_Native_Hawaiian__c] [bit] NULL,
[ASUO_Race_White__c] [bit] NULL,
[ASUO_US_Citizen__c] [bit] NULL,
[Corporate_Logo__c] [nvarchar] (1300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Follow_up_Needed__c] [bit] NULL,
[Last_Outreach_Escalated_Date__c] [datetime] NULL,
[Is_Q_T_completed__c] [bit] NULL,
[Q_T_Completed_Time_Stamp__c] [datetime] NULL,
[ASUO_Lead_Class__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASUO_Lead_SubClass__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Corporate_Affiliation__c] [bit] NULL,
[ASUO_Visa_Type__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Outreach_Escalated__c] [bit] NULL,
[XID__c] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Digital_Experience_Date__c] [datetime] NULL,
[ASURITE_Active__c] [bit] NULL,
[ASU_Affiliation_Alum__c] [bit] NULL,
[ASU_Affiliation_App__c] [bit] NULL,
[ASU_Affiliation_Employee__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASU_Affiliation_Student__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Application_Complete_Date__c] [datetime] NULL,
[Athlete__c] [bit] NULL,
[First_Generation__c] [bit] NULL,
[International__c] [bit] NULL,
[Marital_Status__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[National_Service__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Residency__c] [bit] NULL,
[Undergraduate_Major__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Unspecified__c] [bit] NULL,
[Veteran_Description__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ASUO_SBUX_Partner_ID__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Do_Not_Call_Reason__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email_EMPLID_Change_History__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Enrolled__c] [bit] NULL,
[Application_Complete__c] [bit] NULL,
[Application_Denied_Date__c] [datetime] NULL,
[Application_Denied__c] [bit] NULL,
[Application_Submitted_Date__c] [datetime] NULL,
[Application_Submitted__c] [bit] NULL,
[Closed_Lost_Date__c] [datetime] NULL,
[Closed_Lost__c] [bit] NULL,
[Contact_Made_Date__c] [datetime] NULL,
[Contact_Made__c] [bit] NULL,
[Deemed_Not_Admissible_Date__c] [datetime] NULL,
[Deemed_Not_Admissible__c] [bit] NULL,
[Earned_Admissions_Admissible_Date__c] [datetime] NULL,
[Earned_Admissions_Admissible__c] [bit] NULL,
[Enrolled_for_Course_Date__c] [datetime] NULL,
[Enrolled_for_Course__c] [bit] NULL,
[New_RFI_Date__c] [datetime] NULL,
[New_RFI__c] [bit] NULL,
[QT_Completed_Date__c] [datetime] NULL,
[QT_Completed__c] [bit] NULL,
[QT_Earned_Admissions_Eligible_Date__c] [datetime] NULL,
[QT_Earned_Admissions_Eligible__c] [bit] NULL,
[Started_Application_Date__c] [datetime] NULL,
[Started_Application__c] [bit] NULL,
[Student_Admitted_Date__c] [datetime] NULL,
[Student_Admitted__c] [bit] NULL,
[Applicant_OSPP_App_Needed__c] [bit] NULL,
[Applicant_OSPP_App_Needed_Date__c] [date] NULL,
[copyloaddate] [datetime] NULL CONSTRAINT [DF__Contact__copyloa__7A672E12] DEFAULT (getdate()),
[EA_Learner_Application__c] [nvarchar] (18) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Nitro_handoff__c] [bit] NULL,
[Admit_Term__c] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Admit_date__c] [date] NULL,
[P2A_EA_Checklist_Status__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[P2A_EA_Opt_In_date__c] [date] NULL,
[P2A_EA_Opt_Out_date__c] [date] NULL,
[P2A_Pathway_Sent__c] [bit] NULL,
[P2A_Wait_Designation__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pathway_Notes__c] [nvarchar] (500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)
GO
ALTER TABLE [prodcopy].[Contact] ADD CONSTRAINT [PK__Contact__3214EC07C3ABBBE3] PRIMARY KEY CLUSTERED  ([Id])
GO
